# Esercizi
## Espressioni Regolari

1. Crea un'espressione regolare che fa match solo con parole la cui prima lettera è maiuscola, le altre minuscole.

In [2]:
import re
# ES1

test_string = "THIS is a Test fOR the RegEx"
regex_upperlower = r"\b[A-Z][a-z]+\b"

print(re.findall(regex_upperlower, test_string))

['Test']



2. Scrivi un espressione regolare che trova gli anni dal 1900 al 1999

In [3]:
# ES2
test_string = "1990 1873 19000"
regex_upperlower = r"\b19[0-9]{2}\b"

print(re.findall(regex_upperlower, test_string))

['1990']



2. Crea  un'espressione regolare che estrae anno, mese, giorno di ciascuna data in un testo che contiene date nella forma `aaaa/mm/gg` (dove `a` rappresenta una cifra dell'anno, `m` del mese, `d` del giorno).

In [4]:
# ES3

test_string = "2026/04/22"
regex_date = "([0-9]{4})/([0-9]{2})/([0-9]{2})"

print(re.findall(regex_date, test_string))
match = re.search(regex_date, test_string)
print(f"year is {match.group(1)}")
print(f"month is {match.group(2)}")
print(f"day is {match.group(3)}")

[('2026', '04', '22')]
year is 2026
month is 04
day is 22



3. Data l'espressione regolare precedente, crea una funzione che prende in input una stringa e restituisce una lista di dizionari che contengono i campi `day`, `month` e `year` correttamente popolati usando i valori estratti dall'espressione regolare.

In [5]:
# ES3

def extract_date(text):
    regex_date = "([0-9]{4})/([0-9]{2})/([0-9]{2})"
    result_list = []
    for match in re.finditer(regex_date, text):
        year = match.group(1)
        month = match.group(2)
        day = match.group(3)

        result_list.append({"year": year, 
                            "month": month,
                            "day":day})


    return result_list

test_string = "from 2002/10/23 to 2010/11/12"
print(extract_date(test_string))

[{'year': '2002', 'month': '10', 'day': '23'}, {'year': '2010', 'month': '11', 'day': '12'}]



4. Data l'espressione regolare precedente, crea una funzione che rimpiazza il mese con il mese successivo (attenzione: ci sono solo 12 mesi in un anno)

In [11]:
# ES4
def add_one_month(text): # it only works on a single date in a string
    regex_date = "([0-9]{4})/([0-9]{2})/([0-9]{2})"
    date_match = re.search(regex_date, text)
    month = int(date_match.group(2))
    year = int(date_match.group(1))
    if month == 12:
        month = 1
        year +=1
    else:
        month +=1
    return re.sub(regex_date, rf"{year}/{month:02d}/\3", text)

# WARNING: this does not handle months having a different number of days
print(add_one_month("2025/05/06"))
print(add_one_month("2025/12/06"))

2025/06/06
2026/01/06


5. Uno scrittore sbadato a volte scorda di scrivere una "u" dopo "q", altre volte scrive due "u" dopo "q". Correggi questi errori usando un'espressione regolare

In [13]:
# ES5
def fix_qu_mistakes(text):
    qu_regex = "qu*"
    return re.sub(qu_regex, "qu", text)

print(fix_qu_mistakes("quuuando quali questi"))
print(fix_qu_mistakes("acqa qando"))

quando quali questi
acqua quando


6. Scrivi una funzione che tokenizza tutte le parole in una stringa

In [15]:
# ES6
def tokenize(string):
    one_word_re = r"\w+"
    return re.findall(one_word_re, string)

print(tokenize("a good day to write some Python"))

['a', 'good', 'day', 'to', 'write', 'some', 'Python']


## Numpy

1. Crea un Numpy array di numeri interi da 0 a 19.

In [9]:
import numpy as np
# ES1

array = np.arange(0, 20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


2. Trasforma l'array creato in precedenza in array bidimensionale, la cui prima dimensione ha 4 elementi.

In [11]:
# ES2
array_reshaped = array.reshape((4,5))
print(array_reshaped)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



3. Dato l'array `test_variable`, calcola il valore medio dell'array. Puoi usare `np.sum(test_variable)` per ottenere la somma di tutti i valori dell'array.

In [20]:
import numpy as np
test_variable = np.array([[62, 92],
       [82,  8],
       [35, 84],
       [89, 58],
       [99, 69],
       [74, 69],
       [49, 88],
       [22, 73],
       [16, 14],
       [40, 69]])

def compute_mean_manual(array):
       return np.sum(array) / array.size

print(compute_mean_manual(test_variable))

print(np.mean(test_variable)) # there is also and ad-hoc function

59.6
59.6


3. Dati gli array `array1` e `array2`, somma i valori dell'ultima riga di `array2` a tutte le righe di `array1` 

In [21]:
#ES3

array1 = np.array([[1,2,3,4],[5,6,7,8]])
array2 = np.array([[0,3,6,9],[10,4,33,42]])

print(array2[-1] + array1)

[[11  6 36 46]
 [15 10 40 50]]


4. Scrivi una funzione che ritorna un array composto solo dalle righe e dalle colonne di indice dispari di un array bidimensionale (usa slicing). Se l'array ha un numero di dimensioni diverso da due stampa un errore e ritorna `None`

In [23]:
# ES4
# an bidimensional array from 0 to 100 to test
test_array = np.arange(100).reshape((10,10)) 
test_wrong_array = np.zeros((5,3,12))

def even_rows_columns(array):
    if array.ndim != 2:
        print("ERROR: ndim different than 2")
        return None
    return array[1::2,1::2]

print(even_rows_columns(test_array))
print(even_rows_columns(test_wrong_array))

[[11 13 15 17 19]
 [31 33 35 37 39]
 [51 53 55 57 59]
 [71 73 75 77 79]
 [91 93 95 97 99]]
ERROR: ndim different than 2
None


5. Dati gli array `array1` e `array2`, sottrai gli ultimi tre valori dell'ultima riga di `array2` da tutte le righe di `array1` (suggerimento: serve fare slicing)

In [24]:
# ES5

array1 = np.array([[1,2,3],[6,7,8]])
array2 = np.array([[0,3,6,9],[10,4,33,42]])

print(array1 - array2[:,-3:])

[[ -2  -4  -6]
 [  2 -26 -34]]
